// Group 42:
// R Vijay Krishna 2017A7PS0183P
// Rohit K 2017A7PS0177P

#include "common.h"
#include "hash_table.h"
#include "lexer.h"
#include "parser.h"
#include "time.h"

extern HashTable* keyword_table;
extern unsigned long (*hash_fun)(char*); // Function Pointer to the Hash Function
extern Keyword keywords[];

int main(int argc, char* argv[]) {
    if (argc != 2 && argc != 3) {
        fprintf(stderr, "Format: %s <input> <output>\n", argv[0]);
        exit(EXIT_FAILURE);
    }
    
    FILE* fp = fopen("grammar_rules.txt", "r");
    Grammar g = populate_grammar(fp);
    fclose(fp);
    
    FirstAndFollow f = ComputeFirstAndFollowSets(g);
    ParseTable p = createParseTable(f, g);
    hash_fun = &hash_func;
    keyword_table = populate_hash_table(keyword_table, keywords, hash_fun);
    
    while(1) {
        printf("\nERPLAG COMPILER MENU OPTIONS:\n");
        printf("0: To exit.\n");
        printf("1: For producing clean code by removal of comments on the console.\n");
        printf("2: For printing the token list generated by the lexer.\n");
        printf("3: For parsing to verify the syntactic correctness of the input source code and printing the Parse Tree in an Inorder Traversal\n");
        printf("4: For printing (on the console) the total time taken by your stage 1 code of lexer and parser to verify the syntactic correctness\n");

        int option;
        scanf("%d",&option);
        
        if (option == 0)
            break;

        else if(option == 1) {
            printf("-------------------------------------------------------------\n");
            remove_comments(argv[1], argv[2]);
            printf("-------------------------------------------------------------\n");
            printf("Cleaned comments!\n");
        }
        else if(option == 2) {
            printf("-------------------------------------------------------------\n");
            run_tokenizer(argv[1]);
            printf("-------------------------------------------------------------\n");
        }
        else if(option == 3) {
            TreeNode* parseTree = generateParseTree(argv[1], p, g);
            printf("-------------------------------------------------------------\n");
            printf("Parse Tree:\n");
            printf("Token\tLine No\tLexeme\t\tNum. Value\t\tParent\t\tIs Leaf\t\tSymbol Type\n");
            printParseTree(parseTree);
            printf("-------------------------------------------------------------\n");
            free_parse_tree(parseTree);
        }
        else if (option == 4) {
            clock_t start_time, end_time;
            double total_CPU_time_lexer, total_CPU_time_parser, total_CPU_time_in_seconds_lexer, total_CPU_time_in_seconds_parser;

            start_time = clock();
            run_tokenizer(argv[1]);
            end_time = clock();
            total_CPU_time_lexer  =  (double) (end_time - start_time);
            total_CPU_time_in_seconds_lexer =   total_CPU_time_lexer / CLOCKS_PER_SEC;

            start_time = clock();
            TreeNode* parseTree = generateParseTree(argv[1], p, g);
            end_time = clock();
            total_CPU_time_parser  =  (double) (end_time - start_time);
            total_CPU_time_in_seconds_parser =   total_CPU_time_parser / CLOCKS_PER_SEC;
            
            printf("--------------------------------------------------------------\n");
            printf("Total CPU Time taken for the Lexer: %.6f\n", total_CPU_time_lexer);
            printf("Total CPU Time in seconds taken for the Lexer: %.6f seconds\n", total_CPU_time_in_seconds_lexer);
                    
            printf("Time CPU Time taken for the Parser: %.6f\n", total_CPU_time_parser);
            printf("Time CPU Time in seconds taken for the Parser: %.6f seconds\n", total_CPU_time_in_seconds_parser);
            printf("--------------------------------------------------------------\n");
            free_parse_tree(parseTree);
        }
        else {
            printf("\nInvalid Option\n");
        }
    }

    free_parse_table(p);
    free_first_and_follow(f);
    free_grammar(g);
    free_table(keyword_table);
    return 0;
}
