# Group 42:
# R.VIJAY KRISHNA 2017A7PS0183P
# ROHIT K 2017A7PS0177P
all:
	gcc -o driver.out driver.c parser.c lexer.c hash_table.c common.c -ggdb3
	gcc -o ast_test.out ast_test.c ast.c parser.c lexer.c hash_table.c common.c -ggdb3
