# Group 42:
# R.VIJAY KRISHNA 2017A7PS0183P
# ROHIT K 2017A7PS0177P
all:
	#gcc -o parser.out parser.c lexer.c hash_table.c common.c -Wall -Wextra
	gcc -o driver.out driver.c parser.c lexer.c hash_table.c common.c
	#gcc -o driver.out driver.c -Wall -Wextra
